apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-chart.fullname" . }}-busybox
  labels:
    {{- include "hello-chart.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "hello-chart.selectorLabels" . | nindent 6 }}-busybox
  template:
    metadata:
      labels:
        {{- include "hello-chart.selectorLabels" . | nindent 8 }}-busybox
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh']
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: DATABASE_URI

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: DATABASE_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: DATABASE_PASSWORD

            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: hello-config
                  key: GREETING
          ports:
            - name: http-busybox
              containerPort: 8099
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              port: 8080
#              path: /health
#            initialDelaySeconds: 15
#            periodSeconds: 5
#            timeoutSeconds: 2
#          readinessProbe:
#            httpGet:
#              port: 8080
#              path: /health
#            initialDelaySeconds: 15
#            periodSeconds: 5
