apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-chart.fullname" . }}-busybox
  labels:
    {{- include "hello-chart.labels" . | nindent 4 }}
spec:
#  type: NodePort
  ports:
#    - name: http
#      port: 4180
#      protocol: TCP
#      targetPort: 4180
    - port: 8099
      targetPort: http-busybox
#      nodePort: 8080
      protocol: TCP
      name: web-busybox
  selector:
    {{- include "hello-chart.selectorLabels" . | nindent 4 }}-busybox
