apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-chart.fullname" . }}-processing
  labels:
    {{- include "hello-chart.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "hello-chart.selectorLabels" . | nindent 6 }}-processing
  template:
    metadata:
      labels:
        {{- include "hello-chart.selectorLabels" . | nindent 8 }}-processing
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      initContainers:  # check if DB is ready, and only continue when true
        - name: check-db-ready
          image: postgres:9.6.5
          command: ['sh', '-c',  'until pg_isready -h myapp-postgresql -p 5432;  do echo waiting for database; sleep 2; done;']
        - name: check-kafka-ready
          image: busybox:latest
          command: ['sh', '-c',  'until nc -z -w2 -v myapp-kafka 9092; do sleep 2s; done; ']
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image_processing.repository }}:{{ .Values.image_processing.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: DATABASE_URI

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: DATABASE_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: DATABASE_PASSWORD

            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: hello-config
                  key: GREETING
          ports:
            - name: http-processing
              containerPort: 8083
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              port: 8080
#              path: /health
#            initialDelaySeconds: 15
#            periodSeconds: 5
#            timeoutSeconds: 2
#          readinessProbe:
#            httpGet:
#              port: 8080
#              path: /health
#            initialDelaySeconds: 15
#            periodSeconds: 5
