apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-chart.fullname" . }}-redis
  labels:
    {{- include "hello-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      targetPort: http-redis
      protocol: TCP
      name: web-redis
  selector:
    {{- include "hello-chart.selectorLabels" . | nindent 4 }}-redis
