apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-chart.fullname" . }}-pay-sys
  labels:
    {{- include "hello-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
#    - name: http
#      port: 4180
#      protocol: TCP
#      targetPort: 4180
    - port: 8081
      targetPort: http-pay-sys
#      nodePort: 8080
      protocol: TCP
      name: web-pay-sys
  selector:
    {{- include "hello-chart.selectorLabels" . | nindent 4 }}-pay-sys
